-- MANUAL: ST32-001 / 킨에몬 (2026-08-28 6색 스타트덱 ST31~36 추가)
-- JP 공홈 series 550032 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[ST32-001]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            count=2,
            op=[[DRAW]],
            player=[[YOU]],
          },
          {
            count=1,
            op=[[TRASH_HAND]],
            player=[[YOU]],
          },
        },
        conditions={},
        costs={
          {
            op=[[ALTERNATIVE_COST]],
            options={
              {
                {
                  count=1,
                  filter={
                    attribute=[[SLASH]],
                  },
                  kinds={
                    [[LEADER]],
                  },
                  op=[[REST_OWN_CARD]],
                },
              },
              {
                {
                  count=1,
                  op=[[REST_DON]],
                },
              },
            },
          },
        },
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[【등장 시】자신의, 속성(참)을 가진 리더나 두웅!! 1장을 레스트로 할 수 있다：카드를 2장 뽑고, 자신의 패 1장을 버린다.]],
        timings={
          [[ON_PLAY]],
        },
      },
    },
    keywords={},
    rules_id=[[ST32-001]],
    schema_version=1,
  })
end
