-- MANUAL: OP17-112 / 샬롯 링링 (2026-08-28 OP17 세계최강의 전사 추가)
-- JP 공홈 series 550117 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[OP17-112]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            duration=[[WHILE_CONDITION]],
            op=[[SET_BASE_POWER]],
            selector={
              count=0,
              filter={
                base_power_eq=4000,
                has_trigger=true,
              },
              kind=[[CHARACTER]],
              mode=[[ALL]],
              owner=[[YOU]],
            },
            value=8000,
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[【자신의 턴 동안】자신의 원래 파워 4000인 【트리거】를 가진 캐릭터 전부를 원래 파워 8000으로 한다.]],
        timings={
          [[CONTINUOUS_YOUR_TURN]],
        },
      },
      {
        actions={
          {
            count=1,
            op=[[DRAW]],
            player=[[YOU]],
          },
          {
            op=[[CHOOSE]],
            options={
              {
                {
                  count=1,
                  mode=[[UP_TO]],
                  op=[[ADD_LIFE_FROM_DECK_TOP]],
                  player=[[YOU]],
                },
              },
              {
                {
                  count=1,
                  mode=[[UP_TO]],
                  op=[[TAKE_LIFE_TO_HAND]],
                  player=[[OPPONENT]],
                },
              },
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E2]],
        once_per_turn=false,
        source_text=[[【등장 시】카드를 1장 뽑고, 다음 중 1개를 선택한다.]],
        timings={
          [[ON_PLAY]],
        },
      },
    },
    keywords={},
    rules_id=[[OP17-112]],
    schema_version=1,
  })
end
