-- MANUAL: OP17-063 / 카이도 (2026-08-28 OP17 세계최강의 전사 추가)
-- JP 공홈 series 550117 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[OP17-063]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            amount=1000,
            duration=[[RULE]],
            op=[[MODIFY_COUNTER]],
            selector={
              count=0,
              filter={
                counter_eq=0,
              },
              kind=[[CHARACTER]],
              mode=[[ALL]],
              owner=[[YOU]],
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[자신의 패의 카운터를 가지지 않는 캐릭터 카드 전부는 카운터 +1000을 가진다.]],
        timings={
          [[CONTINUOUS]],
        },
      },
      {
        actions={
          {
            duration=[[THIS_TURN]],
            op=[[NEGATE_EFFECTS]],
            selector={
              count=1,
              filter={
                cost_lte=6,
              },
              kind=[[CHARACTER]],
              mode=[[UP_TO]],
              owner=[[OPPONENT]],
            },
          },
          {
            op=[[KO]],
            selector={
              count=1,
              kind=[[LAST_TARGET]],
              mode=[[UP_TO]],
              owner=[[CONTEXT]],
            },
          },
        },
        conditions={
          {
            op=[[SELF_PLAYED_THIS_TURN]],
            player=[[YOU]],
          },
        },
        costs={
          {
            count=1,
            op=[[RETURN_DON]],
          },
        },
        effect_id=[[E2]],
        once_per_turn=true,
        source_text=[[【기동 메인】【턴 1회】두웅!!-1：이 캐릭터가 등장한 턴인 경우, 상대의 코스트 6 이하인 캐릭터 1장까지를 이번 턴 동안 효과를 무효로 하고, KO한다.]],
        timings={
          [[ACTIVATE_MAIN]],
        },
      },
    },
    keywords={},
    rules_id=[[OP17-063]],
    schema_version=1,
  })
end
