-- MANUAL: OP17-117 / 메이저 사브르 (2026-08-28 OP17 세계최강의 전사 추가)
-- JP 공홈 series 550117 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[OP17-117]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            amount=3000,
            duration=[[THIS_BATTLE]],
            op=[[MODIFY_POWER]],
            selector={
              count=1,
              filter={
                name=[[샬롯 링링]],
              },
              kind=[[LEADER_OR_CHARACTER]],
              mode=[[UP_TO]],
              owner=[[YOU]],
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[【카운터】자신의 「샬롯 링링」 1장까지를 이번 배틀 동안 파워 +3000.]],
        timings={
          [[COUNTER]],
        },
      },
      {
        actions={
          {
            op=[[OPPONENT_CHOOSES]],
            option_conditions={
              {
                {
                  count=3,
                  op=[[HAND_GTE]],
                  player=[[OPPONENT]],
                },
              },
              {},
            },
            options={
              {
                {
                  count=3,
                  op=[[TRASH_HAND]],
                  player=[[OPPONENT]],
                },
              },
              {
                {
                  op=[[KO]],
                  selector={
                    count=1,
                    filter={
                      cost_lte=6,
                    },
                    kind=[[CHARACTER]],
                    mode=[[UP_TO]],
                    owner=[[OPPONENT]],
                  },
                },
              },
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[T1]],
        once_per_turn=false,
        source_text=[[상대는 자신의 패 3장을 버려도 된다. 그렇게 하지 않았을 경우, 상대의 코스트 6 이하인 캐릭터 1장까지를 KO한다.]],
        timings={
          [[LIFE_TRIGGER]],
        },
      },
    },
    keywords={},
    rules_id=[[OP17-117]],
    schema_version=1,
  })
end
