-- MANUAL: ST32-004 / 실버즈 레일리 (2026-08-28 6색 스타트덱 ST31~36 추가)
-- JP 공홈 series 550032 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[ST32-004]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            keyword=[[RUSH]],
            op=[[GAIN_KEYWORD]],
            selector={
              count=1,
              kind=[[SELF]],
              mode=[[UP_TO]],
              owner=[[YOU]],
            },
          },
        },
        conditions={
          {
            attribute=[[SLASH]],
            op=[[LEADER_HAS_ATTRIBUTE]],
            player=[[YOU]],
          },
        },
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[자신의 리더가 속성(참)을 가진 경우, 이 캐릭터는 【속공：캐릭터】를 얻는다.]],
        timings={
          [[CONTINUOUS]],
        },
      },
      {
        actions={
          {
            op=[[CANNOT_ATTACK_LEADER]],
            selector={
              count=1,
              kind=[[SELF]],
              mode=[[ALL]],
              owner=[[YOU]],
            },
          },
        },
        conditions={
          {
            attribute=[[SLASH]],
            op=[[LEADER_HAS_ATTRIBUTE]],
            player=[[YOU]],
          },
          {
            op=[[SELF_PLAYED_THIS_TURN]],
            player=[[YOU]],
          },
        },
        costs={},
        effect_id=[[E1b]],
        once_per_turn=false,
        source_text=[[자신의 리더가 속성(참)을 가진 경우, 이 캐릭터는 【속공：캐릭터】를 얻는다.]],
        timings={
          [[CONTINUOUS]],
        },
      },
      {
        actions={
          {
            op=[[REST]],
            selector={
              count=2,
              filter={
                cost_lte=2,
              },
              kind=[[CHARACTER]],
              mode=[[UP_TO]],
              owner=[[OPPONENT]],
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E2]],
        once_per_turn=false,
        source_text=[[【등장 시】상대의 코스트 2 이하인 캐릭터 2장까지를 레스트로 한다.]],
        timings={
          [[ON_PLAY]],
        },
      },
    },
    keywords={},
    rules_id=[[ST32-004]],
    schema_version=1,
  })
end
