-- MANUAL: ST35-004 / 코알라 (2026-08-28 6색 스타트덱 ST31~36 추가)
-- JP 공홈 series 550035 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[ST35-004]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            keyword=[[BLOCKER]],
            op=[[GAIN_KEYWORD]],
            selector={
              count=1,
              kind=[[SELF]],
              mode=[[UP_TO]],
              owner=[[YOU]],
            },
          },
          {
            amount=1,
            op=[[MODIFY_COST]],
            selector={
              count=1,
              kind=[[SELF]],
              mode=[[UP_TO]],
              owner=[[YOU]],
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[이 캐릭터는 【블로커】를 얻고, 코스트 +1.]],
        timings={
          [[CONTINUOUS]],
        },
      },
      {
        actions={
          {
            count=1,
            mode=[[UP_TO]],
            op=[[GIVE_DON]],
            selector={
              count=1,
              kind=[[LEADER]],
              mode=[[ALL]],
              owner=[[YOU]],
            },
            state=[[RESTED]],
          },
          {
            count=1,
            filter={
              card_type=[[CHARACTER]],
              power_lte=4000,
              trait=[[혁명군]],
            },
            mode=[[UP_TO]],
            op=[[PLAY_FROM_HAND_OR_TRASH]],
            player=[[YOU]],
            rested=false,
          },
        },
        conditions={},
        costs={},
        effect_id=[[E2]],
        once_per_turn=false,
        source_text=[[【등장 시】자신의 리더에 레스트 상태인 두웅!! 1장까지를 부여한다. 그 후, 자신의 패나 트래시에서 파워 4000 이하인 특징 《혁명군》을 가진 캐릭터 카드 1장까지를 등장시킨다.]],
        timings={
          [[ON_PLAY]],
        },
      },
    },
    keywords={},
    rules_id=[[ST35-004]],
    schema_version=1,
  })
end
