-- MANUAL: ST36-005 / 유스타스 키드 (2026-08-28 6색 스타트덱 ST31~36 추가)
-- JP 공홈 series 550036 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[ST36-005]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            op=[[CHANGE_ATTACK_TARGET]],
            selector={
              count=1,
              filter={
                base_power_gte=5000,
                name=[[유스타스 키드]],
              },
              kind=[[LEADER_OR_CHARACTER]],
              mode=[[EXACT]],
              owner=[[YOU]],
            },
          },
        },
        conditions={},
        costs={
          {
            op=[[ALTERNATIVE_COST]],
            options={
              {
                {
                  count=1,
                  faceup=false,
                  op=[[FLIP_LIFE_TOP]],
                },
              },
              {
                {
                  count=1,
                  faceup=false,
                  op=[[FLIP_LIFE_TOP]],
                  position=[[BOTTOM]],
                },
              },
            },
          },
        },
        effect_id=[[E1]],
        once_per_turn=true,
        source_text=[[【상대의 어택 시】【턴 1회】자신의 라이프 위나 아래에서 1장을 뒷면으로 할 수 있다：어택 대상을 자신의 원래 파워 5000 이상인 「유스타스 키드」로 변경한다.]],
        timings={
          [[ON_OPPONENT_ATTACK]],
        },
      },
      {
        actions={
          {
            count=1,
            mode=[[UP_TO]],
            op=[[GIVE_DON]],
            selector={
              count=1,
              kind=[[LEADER]],
              mode=[[ALL]],
              owner=[[YOU]],
            },
            state=[[RESTED]],
          },
        },
        conditions={},
        costs={
          {
            op=[[ALTERNATIVE_COST]],
            options={
              {
                {
                  count=1,
                  op=[[FLIP_LIFE_TOP]],
                },
              },
              {
                {
                  count=1,
                  op=[[FLIP_LIFE_TOP]],
                  position=[[BOTTOM]],
                },
              },
            },
          },
        },
        effect_id=[[E2]],
        once_per_turn=true,
        source_text=[[【기동 메인】【턴 1회】자신의 라이프 위나 아래에서 1장을 앞면으로 할 수 있다：자신의 리더에 레스트 상태인 두웅!! 1장까지를 부여한다.]],
        timings={
          [[ACTIVATE_MAIN]],
        },
      },
    },
    keywords={},
    rules_id=[[ST36-005]],
    schema_version=1,
  })
end
