-- MANUAL: OP17-005 / 에드워드 뉴게이트 (2026-08-28 OP17 세계최강의 전사 추가)
-- JP 공홈 series 550117 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[OP17-005]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            amount=-4,
            conditions={
              {
                filter={
                  power_gte=10000,
                },
                op=[[CHARACTER_EXISTS]],
                player=[[OPPONENT]],
              },
            },
            duration=[[WHILE_CONDITION]],
            op=[[MODIFY_HAND_COST]],
            player=[[YOU]],
            selector={
              count=1,
              kind=[[SELF]],
              mode=[[UP_TO]],
              owner=[[YOU]],
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[패의 이 카드는, 상대의 파워 10000 이상인 캐릭터가 있을 경우, 코스트 -4.]],
        timings={
          [[CONTINUOUS]],
        },
      },
      {
        actions={
          {
            duration=[[UNTIL_OPPONENT_NEXT_TURN_END]],
            op=[[SET_BASE_POWER]],
            selector={
              count=1,
              kind=[[LEADER]],
              mode=[[EXACT]],
              owner=[[YOU]],
            },
            value=8000,
          },
        },
        conditions={
          {
            negate=true,
            op=[[LEADER_IS_MULTICOLOR]],
            player=[[YOU]],
          },
        },
        costs={},
        effect_id=[[E2]],
        once_per_turn=false,
        source_text=[[【등장 시】자신의 단색 리더를 다음 상대의 엔드 페이즈 종료 시까지 원래 파워 8000으로 한다.]],
        timings={
          [[ON_PLAY]],
        },
      },
    },
    keywords={},
    rules_id=[[OP17-005]],
    schema_version=1,
  })
end
