-- MANUAL: OP17-049 / 샬롯 링링 (2026-08-28 OP17 세계최강의 전사 추가)
-- JP 공홈 series 550117 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[OP17-049]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            op=[[OPPONENT_CHOOSES]],
            options={
              {
                {
                  count=2,
                  op=[[DRAW]],
                  player=[[YOU]],
                },
              },
              {
                {
                  count=2,
                  op=[[TRASH_HAND]],
                  player=[[OPPONENT]],
                },
              },
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[【등장 시】상대는 다음 중 1개를 선택한다.]],
        timings={
          [[ON_PLAY]],
        },
      },
      {
        actions={
          {
            amount=1000,
            duration=[[THIS_BATTLE]],
            op=[[MODIFY_POWER]],
            selector={
              count=1,
              kind=[[LEADER_OR_CHARACTER]],
              mode=[[UP_TO]],
              owner=[[YOU]],
            },
          },
        },
        conditions={},
        costs={
          {
            count=1,
            op=[[TRASH_HAND]],
          },
        },
        effect_id=[[E2]],
        once_per_turn=true,
        source_text=[[【상대의 어택 시】【턴 1회】자신의 패 1장을 버릴 수 있다：자신의 리더나 캐릭터 1장까지를 이번 배틀 동안 파워 +1000.]],
        timings={
          [[ON_OPPONENT_ATTACK]],
        },
      },
    },
    keywords={},
    rules_id=[[OP17-049]],
    schema_version=1,
  })
end
