-- MANUAL: ST32-003 / 쥬라큘 미호크 (2026-08-28 6색 스타트덱 ST31~36 추가)
-- JP 공홈 series 550032 기준, OP16 이식 방식 준수.
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[ST32-003]],
    compile_status=[[MANUAL]],
    effects={
      {
        actions={
          {
            count=1,
            op=[[DRAW]],
            player=[[YOU]],
          },
          {
            count=1,
            op=[[TRASH_HAND]],
            player=[[YOU]],
          },
        },
        conditions={
          {
            op=[[YOUR_TURN]],
          },
        },
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[【자신의 턴 동안】이 캐릭터가 레스트가 되었을 때, 카드를 1장 뽑고, 자신의 패 1장을 버린다.]],
        timings={
          [[ON_SELF_RESTED]],
        },
      },
      {
        actions={
          {
            count=1,
            filter={
              any={
                {
                  name=[[페로나]],
                },
                {
                  attribute=[[SLASH]],
                },
              },
              card_type=[[CHARACTER]],
              cost_lte=5,
            },
            mode=[[UP_TO]],
            op=[[PLAY_FROM_HAND]],
            player=[[YOU]],
            rested=false,
          },
        },
        conditions={
          {
            attribute=[[SLASH]],
            op=[[LEADER_HAS_ATTRIBUTE]],
            player=[[YOU]],
          },
        },
        costs={},
        effect_id=[[E2]],
        once_per_turn=false,
        source_text=[[【등장 시】자신의 리더가 속성(참)을 가진 경우, 자신의 패에서 코스트 5 이하인, 「페로나」나 속성(참)을 가진 캐릭터 카드 1장까지를 등장시킨다.]],
        timings={
          [[ON_PLAY]],
        },
      },
    },
    keywords={},
    rules_id=[[ST32-003]],
    schema_version=1,
  })
end
