-- AUTO-GENERATED: OP14-104 / 겟코 모리아
-- rules_id=OP14-104 script_id=880002269 fingerprint=b6fc3e8b19b2f517ae6c767ab2e6324db11eebef075ad1280edd338699da1715
local s,id=GetID()
function s.initial_effect(c)
  opcg.RegisterCard(c,{
    base_card_no=[[OP14-104]],
    compile_status=[[AUTO]],
    effects={
      {
        actions={
          {
            count=1,
            op=[[CHOOSE]],
            options={
              {
                {
                  count=1,
                  destination=[[LIFE_TOP]],
                  faceup=true,
                  mode=[[UP_TO]],
                  op=[[ADD_TO_LIFE]],
                  selector={
                    count=1,
                    filter={
                      card_type=[[CHARACTER]],
                      cost_lte=4,
                      trait=[[스릴러 바크 해적단]],
                    },
                    kind=[[TRASH]],
                    mode=[[UP_TO]],
                    owner=[[YOU]],
                  },
                },
              },
              {
                {
                  count=1,
                  filter={
                    card_type=[[CHARACTER]],
                    cost_lte=4,
                    trait=[[스릴러 바크 해적단]],
                  },
                  mode=[[UP_TO]],
                  op=[[PLAY_FROM_TRASH]],
                  player=[[YOU]],
                  rested=false,
                },
              },
            },
          },
        },
        conditions={},
        costs={},
        effect_id=[[E1]],
        once_per_turn=false,
        source_text=[[【등장 시】자신의 트래시에서 코스트 4 이하인 《스릴러 바크 해적단》 특징을 가진 캐릭터 카드 1장까지를, 라이프 맨 위에 앞면으로 더하거나 등장시킨다.]],
        timings={
          [[ON_PLAY]],
        },
      },
      {
        actions={
          {
            count=1,
            filter={
              card_type=[[CHARACTER]],
              cost_lte=4,
            },
            mode=[[UP_TO]],
            op=[[PLAY_FROM_TRASH]],
            player=[[YOU]],
            rested=false,
          },
        },
        conditions={},
        costs={},
        effect_id=[[T1]],
        once_per_turn=false,
        source_text=[[자신의 트래시에서 코스트 4 이하인 캐릭터 카드 1장까지를 등장시킨다.]],
        timings={
          [[LIFE_TRIGGER]],
        },
      },
    },
    keywords={},
    rules_id=[[OP14-104]],
    schema_version=1,
  })
end
